import type { Job } from "../types/job";

export const Mockjobs: Job[] = [
  {
    id: 1,
    company: "Google",
    role: "Frontend Engineer",
    appliedAt: "2025-01-12",
    status: "interview",
    interviewType: "Virtual",
    interviewDate: "2025-01-20",
    companyEmail: "recruiting@google.com",
    salaryExpectation: 85000,
    personalRating: "Very promising – strong team",
    jobType: "Full Time",
    workType: "Hybrid",
  },
  {
    id: 2,
    interviewDate: "2025-01-20",
    company: "Stripe",
    role: "Product Engineer",
    appliedAt: "2025-01-05",
    status: "applied",
    companyEmail: "jobs@stripe.com",
    salaryExpectation: 78000,
    personalRating: "Waiting for response",
    jobType: "Full Time",
    workType: "Remote",
  },
  {
    id: 3,
    company: "Microsoft",
    role: "Software Engineer",
    appliedAt: "2024-12-28",
    status: "offer",
    interviewType: "In-person",
    interviewDate: "2025-01-15",
    companyEmail: "careers@microsoft.com",
    salaryExpectation: 90000,
    personalRating: "Offer received 🎉",
    jobType: "Full Time",
    workType: "On-Site",
  },
  {
    id: 4,
    company: "Meta",
    role: "UI Engineer",
    appliedAt: "2024-12-20",
    status: "rejected",
    interviewType: "Virtual",
    interviewDate: "2024-12-30",
    companyEmail: "meta-careers@meta.com",
    salaryExpectation: 82000,
    personalRating: "Good interview process, no offer",
    jobType: "Full Time",
    workType: "Hybrid",
  },
  {
    id: 5,
    company: "Paystack",
    role: "Frontend Developer",
    appliedAt: "2025-01-08",
    status: "interview",
    interviewType: "In-person",
    interviewDate: "2025-01-22",
    companyEmail: "talent@paystack.com",
    salaryExpectation: 60000,
    personalRating: "Local company with strong culture",
    jobType: "Full Time",
    workType: "On-Site",
  },
];
