import type { ContactPayload } from "../types/types";

export const MOCK_CONTACTS: ContactPayload[] = [
  {
    id: 101,
    name: "Marcus Holloway",
    role: "Lead Security Researcher",
    email: "m.holloway@dedsec.org",
    phoneNumber: "415-555-0198",
    socialLinks: ["https://twitter.com/retsec", "https://github.com/mholloway"],
  },
  {
    id: "cf-202",
    name: "Elena Rodriguez",
    role: "UI/UX Designer",
    email: "elena.design@studio.com",
    phoneNumber: 12125550456,
    socialLinks: [
      "https://behance.net/erodriguez",
      "https://dribbble.com/elena_draws",
    ],
  },
  {
    id: 103,
    name: "Julian Chen",
    role: "DevOps Engineer",
    email: "j.chen@cloudstack.io",
    phoneNumber: "+44-20-7946-0958",
    socialLinks: ["https://linkedin.com/in/jchen-devops"],
  },
  {
    id: "cf-404",
    name: "Sarah Jenkins",
    role: "Technical Writer",
    email: "s.jenkins@docuhelp.net",
    phoneNumber: 14155552671,
    socialLinks: [],
  },
  {
    id: 105,
    name: "Amara Okafor",
    role: "Data Scientist",
    email: "amara.o@analytics-pro.com",
    phoneNumber: "234-803-555-1234",
    socialLinks: ["https://kaggle.com/amarao", "https://github.com/aokafor"],
  },
  {
    id: "cf-606",
    name: "Leo Takahashi",
    role: "Frontend Developer",
    email: "leo.t@webflow.jp",
    phoneNumber: 81355501092,
    socialLinks: ["https://twitter.com/leotaka_web"],
  },
  {
    id: 107,
    name: "Isabella Rossi",
    role: "Product Manager",
    email: "i.rossi@fintech-global.com",
    phoneNumber: "+39-02-555-012",
    socialLinks: ["https://linkedin.com/in/rossi-isabella"],
  },
  {
    id: "cf-808",
    name: "David Miller",
    role: "Backend Architect",
    email: "d.miller@systems-arch.com",
    phoneNumber: 16505550843,
    socialLinks: ["https://github.com/dmiller-backend"],
  },
  {
    id: 109,
    name: "Chloe Dupont",
    role: "QA Engineer",
    email: "c.dupont@testlabs.fr",
    phoneNumber: "+33-1-555-01-99",
    socialLinks: ["https://linkedin.com/in/cdupont-qa"],
  },
  {
    id: "cf-010",
    name: "Omar Al-Farsi",
    role: "Fullstack Developer",
    email: "omar.f@tech-hub.ae",
    phoneNumber: 97145550123,
    socialLinks: ["https://github.com/omar-farsi", "https://omar-dev.me"],
  },
];
